config/routes.rb
Sparum::Application.routes.draw do
  devise_for :users

  devise_for :users, :controllers => {:sessions => 'devise/sessions', :registrations => 'devise/registrations'} do
    get "/login", :to => "devise/sessions#new", :as => :login
    get "/register", :to => "devise/regisrations#new", :as => :register
    delete "/logout", :to => "devise/sessions#destroy", :as => :logout
  end

  resources :forums, :only => [:show, :index]

  namespace :admin do
    resources :forums

    root :to => 'dashboard#index'
  end

  root :to => 'forums#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    @user = user || User.new
    if @user.admin?
      can :manage, :all
    else
      can :read, :all
    end    
  end 
  

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  
end

app/models/forum.rb
class Forum < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base  
  include Enumerize

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  enumerize :role, in: %w[admin moder user guest], default: :guest

  role.values.each do |r|
    define_method "#{r}?" do
      self.role == r
    end
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :authenticate_user!  

  layout 'admin'
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def index
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base  
  protect_from_forgery    

  before_filter :authenticate_user!, except: ['index', 'show'] 

  #load_and_authorize_resource

  self.responder = ApplicationResponder

  respond_to :html
end

app/controllers/application_responders.rb
class ApplicationResponder < ActionController::Responder
  include Responders::FlashResponder
  include Responders::HttpCacheResponder
end

app/controllers/default_controller.rb
class DefaultController < ApplicationController
  def index    
  end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  load_and_authorize_resource
end

app/helpers/application_helper.rb
module ApplicationHelper
  #TODO: refactoring
  def show_flash(name, msg)
    html_class = 'alert'
    html_class += ' alert-success' if name == :notice
    html_class += ' alert-error' if name == :error

    btn_close = button_tag '&times;'.html_safe, 'data-dismiss'.to_sym => 'alert', type: 'button', class: 'close'

    content_tag :div, btn_close + msg, class: html_class
  end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/admin/dashboard/index.html.slim
= "index.html.slim"

.span4
  .btn-toolbar
    .btn-group
      a href="#" class="btn btn-primary"
        i class="icon-user"
        User

      a href="#" data-toggle="dropdown" class="btn btn-primary dropdown-toggle"
        span.icon-caret-down      

      ul.dropdown-menu
        li
          a href="#"
            i.icon-pencil
            Edit
        li
          a href="#"
            i.icon-trash
              Delete
        li
          a href="#"
            i.icon-ban-circle
            Ban
        li.divider
        li
          a href="#"
            i.i
            Make admin

app/views/admin/forums/_form.html.slim
= simple_form_for @forum, :html => { :class => "form-horizontal" } do |f|
  = f.input :name
  = f.input :topics_count
  = f.input :status
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    '
    = link_to t('.cancel', :default => t("helpers.links.cancel")), forums_path, :class => 'btn'

app/views/admin/forums/edit.html.slim
- model_class = @forum.class
div class="page-header"
  h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/admin/forums/index.html.slim
- model_class = Forum.new.class
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize
table class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:topics_count)
      th= model_class.human_attribute_name(:status)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @forums.each do |forum|
      tr
        td= link_to forum.id, forum_path(forum)
        td= forum.name
        td= forum.topics_count
        td= forum.status
        td=l forum.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_forum_path(forum), :class => 'btn btn-mini'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), forum_path(forum), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

/= link_to t('.new', :default => t("helpers.links.new")), new_forum_path, :class => 'btn btn-primary'

app/views/admin/forums/new.html.slim
- model_class = @forum.class
div class="page-header"
  h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/admin/forums/show.html.slim
- model_class = @forum.class
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human

p
  strong= model_class.human_attribute_name(:name) + ':'
  br
  = @forum.name
p
  strong= model_class.human_attribute_name(:topics_count) + ':'
  br
  = @forum.topics_count
p
  strong= model_class.human_attribute_name(:status) + ':'
  br
  = @forum.status

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), forums_path, :class => 'btn'
  '
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_forum_path(@forum), :class => 'btn'
  '
  = link_to t('.destroy', :default => t("helpers.links.destroy")), forum_path(@forum), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'

app/views/default/index.html.slim
h3 default/index.html.slim

app/views/forums/index.html.slim
h2 Listing forums
- model_class = Forum.new.class
table class="table table-striped"
  thead
    tr      
      th = model_class.human_attribute_name(:name)
      th = model_class.human_attribute_name(:topics_count)      
      th = model_class.human_attribute_name(:created_at)      
  tbody
    - @forums.each do |forum|
      tr        
        td = forum.name
        td = forum.topics_count        
        td = l forum.created_at        

app/views/forums/show.html.slim
p#notice = notice


= link_to 'Edit', edit_forum_path(@forum)
'|
= link_to 'Back', forums_path

app/views/layouts/admin.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Sparum"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    link href="images/favicon.ico" rel="shortcut icon"
    link href="images/apple-touch-icon.png" rel="apple-touch-icon"
    link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"
    link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"

  body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          a.btn.btn-navbar data-target=".nav-collapse" data-toggle="collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.brand href="/admin/" Admin Panel
          .container.nav-collapse
            ul.nav
              li= link_to "Категории", "/admin/"
              li= link_to "Link 2", "/path2"
              li= link_to "Link 3", "/path3"

    .container

      .content
        .row
          .span9
            = yield
          .span3
            .well.sidebar-nav
              h3 Sidebar
              ul.nav.nav-list
                li.nav-header Sidebar
                li= link_to "Link 1", "/path1"
                li= link_to "Link 2", "/path2"
                li= link_to "Link 3", "/path3"
    
      footer
        p &copy; Company 2012
    /!
      Javascripts
      \==================================================
    /! Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Sparum"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    link href="images/favicon.ico" rel="shortcut icon"
    link href="images/apple-touch-icon.png" rel="apple-touch-icon"
    link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"
    link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"

  body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          a.btn.btn-navbar data-target=".nav-collapse" data-toggle="collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.brand href="#"Sparum
          .container.nav-collapse
            ul.nav
              li= link_to "Link 1", "/path1"
              li= link_to "Link 2", "/path2"
              li= link_to "Link 3", "/path3"

    .container

      p.notice = notice if notice.present?
      p.alert = alert if alert.present?

      .content
        .row
          .span9
            = yield
          .span3
            .well.sidebar-nav
              h3 Sidebar
              ul.nav.nav-list
                li.nav-header Sidebar
                li= link_to "Link 1", "/path1"
                li= link_to "Link 2", "/path2"
                li= link_to "Link 3", "/path3"
    
      footer
        p &copy; Company 2012
    /!
      Javascripts
      \==================================================
    /! Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"